### ISSUE TITLE
fitWidth creates one column only

### ISSUE THREAD

**Issue by marti4ka** [wynfred/ngx-masonry#11]
Hi,

thanks for your work on this module 😃I have an issue with `fitWidth`. When I try using it, I only get a single column in the middle of my page. Nothing happens when I resize. When I remove `"fitWidth": true` I have multiple columns, but aligned left 😭Any ideas why this happens?

This is my html:
```
<ngx-masonry class="background-container" data-masonry='{ "itemSelector": ".grid-item", "gutter": 50, "fitWidth": true, "columnWidth": 470 }'>
    <ngxMasonryItem class="masonry-item" *ngFor="let post of posts">
        <post class="grid-item"
        ... >
        </post>
    </ngxMasonryItem>
</ngx-masonry>
```

This is my css:
```
.background-container{
    margin: 0 auto;
}
.masonry-item {
    width: 470px;
}
```

My post also has a container class
```
.container {
    width: 470px;
    border: 1px solid lightgrey;
    border-radius: 5px;
    box-shadow: 3px 3px 3px rgba(0, 0, 0, 0.2);
    padding: 25px 50px;
    margin-bottom: 50px;
    background-color: white;
}
```

**Comment by jorroll** [comment]
Looks like the individual masonry items have the same width as the container? Each `470px` is that right? If so, it makes sense that only one column would fit.

This doesn't really answer your question exactly, but I achieved a two column layout that fills the whole container space using percentage widths for the columns. Assuming you're trying to adjust the column widths to evenly fill the container.

**Comment by marti4ka** [comment]
Thanks for the fast response. 
My items (posts) always have fixed width of 470px. I want the gutter between them to be 50 and the side margins to change when I resize the window. This example is exactly what I need: https://codepen.io/desandro/pen/nGLvx

I tried playing around with the `masonry-item`, `grid-item`, the post `container` etc. but I couldn't find a working combination.

**Comment by dmitry-grinko** [comment]
ngx-masonry{
    width: 100%;
}

**Comment by marcinkurek** [comment]
Hi,

Replying here because I ran into the same problem, but before I solved it I found this issue, and I figured other people might too.

In my case this was caused by `<ngx-masonry>` being the root element in an Angular component, which is an inline element by default. I needed to add the following CSS:

```css
:host {
    display: block;
}
```
