### ISSUE TITLE
No longer being maintained, feel free to take it over.

### ISSUE THREAD

**Issue by gethinoakes** [wynfred/ngx-masonry#13]
As you may have seen from the lack of response to issues, this library is no longer being maintained.

I worked on it when a masonry layout was a requirement for the project I work on at my day job. We no longer use a masonry layout so dedicating my time to this isn't worth it for me. I hardly had any time to dedicate to it anyway.

So if there is someone out there who wants to transfer this repo to your name including the npm library then let me know.

**Comment by wynfred** [comment]
@gethinoakes hello, I understand that you don't have time to maintain this project, but could you update the dependency to support angular 7? I'm using it with v7 and it works fine. I just want to remove the peerDependency warning.
You can also transfer this repo and npm lib to me, and I'll update the dependency and try to support it.
Thanks!

**Comment by experionakash** [comment]
Any updates on this

**Comment by Valindo** [comment]
@gethinoakes , Willing to help maintain this, what do I need to get done?

**Comment by ricardosaracino** [comment]
if someone wants to take ownership ill pitch in with maintenance

**Comment by wynfred** [comment]
@ricardosaracino I updated the dependencies for this lib and published a new package `ng-masonry-layout`. If you are interested you can join and maintain this one.

**Comment by gethinoakes** [comment]
I have just pushed an update to remove the dependency limits.
@wynfred if you want to take ownership of this repo & npm library let me know.
... or anyone else for that matter.

**Comment by wynfred** [comment]
@gethinoakes I would like to. My npm username is the same as github's. Thanks for your work!

**Comment by gethinoakes** [comment]
@wynfred transferred the npm package to you and going to do the same with this github repo now (will also transfer the demo repo).
Thanks and good luck 👍
