### ISSUE TITLE
ngx-masonry is not a known element

### ISSUE THREAD

**Issue by IsaacHub** [wynfred/ngx-masonry#15]
I'm getting the following error. Can someone help me to fix this?

```
core.js:12632 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ngx-masonry' is not a known element:
1. If 'ngx-masonry' is an Angular component, then verify that it is part of this module.
2. If 'ngx-masonry' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by opliz** [comment]
You should install these package:     "imagesloaded": "^4.1.1", "masonry-layout": "^4.2.0" in package.json file. Then using similar code:
`<ngx-masonry (layoutComplete)="layoutComplete($event)" [options]="masonryOptions" [useImagesLoaded]="true">
        <ngxMasonryItem *ngFor="let image of images; let i = index" class="item col-md-4">
          <a (click)="openGallery(i)">
            <img width="100%" src="{{image.src_m}}" alt="{{image.title_o}}" title="{{image.title_o}}">
          </a>
        </ngxMasonryItem>
      </ngx-masonry>`

Or you can custom plugin like this:
https://github.com/opliz/media

**Comment by hugoblanc** [comment]
Same for me. imagesloaded and masonry-layout was already installed

**Comment by jorroll** [comment]
This is a generic Angular error indicating that the component you are trying to use has not been declared in the current module context. You need to add the ngx masonry module to your module's imports array.

**Comment by hugoblanc** [comment]
I was so sure about myself ... 
Module import in home.module and component used into another one ...

**Comment by jorroll** [comment]
It happens to the best of us 👍
