### ISSUE TITLE
Is there a way to force sort?

### ISSUE THREAD

**Issue by ghost** [wynfred/ngx-masonry#17]
When I reload the same page, the order changes.

It may be affected if a particular image is later loaded.

Is there a way to sort in array order?

**Comment by wynfred** [comment]
desandro/masonry doesn't support insert item to in middle of the list so it's hard to keep items ordered when images loaded asynchronously. If you want to force the order of the list, you'll have to load items synchronously. If you can get your image's dimension before the image is loaded, you can put a placeholder in your item and remove usage of imagesloaded to keep the order.

**Comment by ghost** [comment]
@wynfred  Thank you for your reply.
I got a hint on your answer.
I used 'imageloaded', And I gave the delay to array push.
The problem disappeared, but founded problem of mixing the image when changing the browser size using toggle Device Toolbar in Chrome. (Image loading completed status)
Thank you again.

**Comment by wynfred** [comment]
No problem. You need to subscribe to viewport size change and call `layout` function or use the `updateLayout` input.
