### ISSUE TITLE
Problem with dynamic filtering

### ISSUE THREAD

**Issue by barbhackk** [wynfred/ngx-masonry#18]
I use Angular 7 and I want to dynamically filter my tiles like [https://codepen.io/dan10gc/pen/GMBxaN](https://codepen.io/dan10gc/pen/GMBxaN)

Have implemented in a selected class.
So I have an array of items with a title and a category.
When I click on a category, the class is added and I put the element in `display: none`.

Then I reload the layout with updateLayout.

In some cases, it reorganizes all of them on one column. Specifically, if the first tile present in the DOM, is not the one that corresponds to the selected category.

Exemple : 

### Select catégorie : All

| Web     |     Photos    |   Photos |
| ------------- | ------------- | --------- |
| Web     |        Photos        |      Web |
| Apps        |        Photos        |      Photos |
| Apps      |        Web        |      Apps |

### Select catégorie : Web

| Web     |     Web|   Web |
| ------------- | ------------- | --------- |
| Web     |        Web        |      Web |
| ...|        ...|      ...|

### Select catégorie : Photos

| Photos |
| ------------- |
| Photos|
| Photos        |
| Photos      |
|...|

### Select catégorie : Apps

| Apps|
| ------------- |
| Apps|
| Apps|
| Apps|
|...|

Thank you for your help,

**Comment by wynfred** [comment]
Can you try removing the item from the array instead of set it to `display:none`, or use the `itemSelector` option?

**Comment by barbhackk** [comment]
> Can you try removing the item from the array instead of set it to `display:none`, or use the `itemSelector` option?

Hi,

If I use removing the item, when I want to display the items that have been hidden previously, it is added to the following.

The itemSelector don't work. I am forced to use 'ngxMasonryItem'

You can look at my code on this page :
[https://angular-7wyfeh.stackblitz.io](https://angular-7wyfeh.stackblitz.io) for App
[https://stackblitz.com/edit/angular-7wyfeh](https://stackblitz.com/edit/angular-7wyfeh) for Edit

**Comment by barbhackk** [comment]
> > Can you try removing the item from the array instead of set it to `display:none`, or use the `itemSelector` option?
> 
> Hi,
> 
> If I use removing the item, when I want to display the items that have been hidden previously, it is added to the following.
> 
> The itemSelector don't work. I am forced to use 'ngxMasonryItem'
> 
> You can look at my code on this page :
> https://angular-7wyfeh.stackblitz.io for App
> https://stackblitz.com/edit/angular-7wyfeh for Edit

Any solution ? Thanks.

**Comment by wynfred** [comment]
Hi,
You can try this:
`@ViewChild(NgxMasonryComponent, {static: false}) masonry: NgxMasonryComponent;`
And use the `reloadItems` function without `display:none`, in the filter function:
```
this.portfolioItems = this.items.filter(it => (it.cat === cat || cat === 'all'));
setTimeout(() => this.masonry._msnry.reloadItems())
this.updateMasonryLayout = Date.now().toString();
```

**Comment by barbhackk** [comment]
> Hi,
> You can try this:
> `@ViewChild(NgxMasonryComponent, {static: false}) masonry: NgxMasonryComponent;`
> And use the `reloadItems` function without `display:none`, in the filter function:
> 
> ```
> this.portfolioItems = this.items.filter(it => (it.cat === cat || cat === 'all'));
> setTimeout(() => this.masonry._msnry.reloadItems())
> this.updateMasonryLayout = Date.now().toString();
> ```

Thank you it's perfect... I will never have thought of it alone.
You got me out of a sticky situation! Thank you so much.

**Comment by dandohotaru** [comment]
### first take
having hit the wall with the same problem the other day, managed to make it work in conjunction with the proposed `updateLayout` field and `reloadItems` ([stackblitz](https://stackblitz.com/edit/angular-ngx-masonry-filters))

```
  <ngx-masonry [options]="options" [updateLayout]="store.stamp">
    <div ngxMasonryItem *ngFor="let item of store.refined; let i = index">
```
``` 
  @ViewChild(NgxMasonryComponent, {static: false}) 
  public masonry: NgxMasonryComponent;

  public filter(category: string){
    this.store.refined = this.store.cached
      .filter(p => p.category == category || category == 'all');
    this.store.stamp = new Date();
    this.masonry.reloadItems();
  }
```

### second take
this solution though seemed a bit hacky to have to trigger a change detection just to to force masonry to redraw itself.
in the end came up with another solution based on `reloadItems` and `layout` without the need of an `updateLayout` field ([stackblitz](https://stackblitz.com/edit/angular-ngx-masonry-filters-alt))

```
  <ngx-masonry [options]="options">
    <div ngxMasonryItem *ngFor="let item of store.refined; let i = index">
```
```
  @ViewChild(NgxMasonryComponent, {static: false}) 
  public masonry: NgxMasonryComponent;

  public filter(category: string){
    this.store.refined = this.store.cached
      .filter(p => p.category == category || category == 'all');

    setTimeout(() => {
      this.masonry._msnry.reloadItems();
      this.masonry._msnry.layout();
    });
  }
```

adding the link to masonry layout docs just for further references
https://masonry.desandro.com/methods.html

**Comment by zeeshanshanif** [comment]
> Hi,
> You can try this:
> `@ViewChild(NgxMasonryComponent, {static: false}) masonry: NgxMasonryComponent;`
> And use the `reloadItems` function without `display:none`, in the filter function:
> 
> ```
> this.portfolioItems = this.items.filter(it => (it.cat === cat || cat === 'all'));
> setTimeout(() => this.masonry._msnry.reloadItems())
> this.updateMasonryLayout = Date.now().toString();
> ```

how it works without using filter just show items in sequence as they are in array?
