### ISSUE TITLE
Error during AOT build for older Angular version

### ISSUE THREAD

**Issue by olehleskiv** [wynfred/ngx-masonry#2]
I got an error during AOT build
`ERROR in Metadata version mismatch for module /Users/olehleskiv/Documents/projects/geddit-admin-ui/node_modules/ngx-masonry/ngx-masonry.d.ts, found version 4, expected 3`

I think that is because the old Angular version we use on project "`^4.0.0`", but we are not ready to migrate now. Do you have any suggestions to help?

**Comment by gethinoakes** [comment]
Use the library locally and change the dependencies to use ^ 4.0.0
