### ISSUE TITLE
Error when first item is bigger width than other

### ISSUE THREAD

**Issue by barbhackk** [wynfred/ngx-masonry#22]
I use Angular 8.

I implemented a click event on masonry-item.
When I click on an element, I want it to expand by adding a class 'opened'.
But when I click on the first element only, the others are all in columns below instead of being side by side despite the call to the method 'layout ()'.

You can look at my code on this page :
[https://angular-7wyfeh.stackblitz.io](https://angular-7wyfeh.stackblitz.io) for App
[https://stackblitz.com/edit/angular-7wyfeh](https://stackblitz.com/edit/angular-7wyfeh) for Edit

Thank you for your help,

**Comment by barbhackk** [comment]
A little help 😁☺️😭

**Comment by wynfred** [comment]
Hi, you just need the columnWidth option :)
https://masonry.desandro.com/faq.html#the-first-item-breaks-the-grid

**Comment by barbhackk** [comment]
> Hi, you just need the columnWidth option :)
> https://masonry.desandro.com/faq.html#the-first-item-breaks-the-grid

😓 Thanks a lot @wynfred 💪🏻💪🏻💪🏻
