### ISSUE TITLE
Error: Metadata version mismatch for module .../ngx-masonry/ngx-masonry.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by iamsahilralkar** [wynfred/ngx-masonry#23]
Specification:
Angular 4
ngx-masonry 1.1.4

**Comment by iamsahilralkar** [comment]
hi!
After spending a whole day I resolved this issue.
What I did:
In ngx-masonry.metadata.json file I updated the version number from '4' into '3'
and saved the changes and run the project without any error.


please look into it. This may be wrong but it worked for me.

**Comment by wynfred** [comment]
Hi, this library was developed to support angular 5 so it may not work with v4. You can take a look at https://github.com/jelgblad/angular2-masonry if you can't upgrade your angular version.

**Comment by iamsahilralkar** [comment]
> Hi, this library was developed to support angular 5 so it may not work with v4. You can take a look at https://github.com/jelgblad/angular2-masonry if you can't upgrade your angular version.

thank you! will check it out.
