### ISSUE TITLE
css binding (gutter)

### ISSUE THREAD

**Issue by j0nm1** [wynfred/ngx-masonry#24]
Hi, I'm trying to use ngx-masonry in an application for different screen sizes and therefore I need to scale the items and especially the gutter in relation to the screen size. The items are pretty easy, I use a media query to change the size and I'm done.
The problem is that the gutter expects a number but I would like to bind it to a CSS property to use it with the already created media queries. The original masonry library provides such a functionality: https://masonry.desandro.com/options.html#gutter

Can you think of any workaround for me or even implement this feature?

**Comment by wynfred** [comment]
Hi, if this option is supported by the masonry library, it should be supported by this angular component as well. You can try to pass a selector (gutter-sizer) to the gutter option.

**Comment by j0nm1** [comment]
I already tried the following but it has no effect. There is no error but the gutter is not applied:

```
<ngx-masonry class="masonry-content" [options]="{ gutter: gutter-sizer, fitWidth: true, resize: true, initLayout: true}" [useImagesLoaded]="true"> 
      <div ngxMasonryItem class="masonry-item" *ngFor="let item of masonryItems">
       <img src={{item.path}}  (load)="updateStatus()" />
      </div>
    </ngx-masonry>
```
```
.gutter-sizer {
  width: 10px;
}
```

**Comment by wynfred** [comment]
You need an element like `<div class="gutter-sizer"></div>` in the masonry. It won't work if you only have a css class.

**Comment by j0nm1** [comment]
Thanks!
I got it to work with this code:

```
<ngx-masonry class="masonry-content" [options]="{  gutter: '.gutter-sizer', fitWidth: true, resize: true, initLayout: true}" [useImagesLoaded]="true"> 
      <div class="gutter-sizer"></div>
      <div ngxMasonryItem class="masonry-item" *ngFor="let item of masonryItems">
       <img src={{item.path}}  (load)="updateStatus()" />
      </div>
    </ngx-masonry>
```

```
.gutter-sizer {
  width: 20px;
}
```
