### ISSUE TITLE
--prod build animation issue

### ISSUE THREAD

**Issue by madmacc** [wynfred/ngx-masonry#26]
When I build for development it all works fine.

When I build for production the animation to display all of the items runs twice.  The first time a slide in from the bottom and then directly after the images just to the top right and slide in from there.  This happens in both chrome and safari.

```
<ngx-masonry #ngxMasonry [options]="masonryOptions" [updateLayout]="updateMasonryLayout">
  <mat-card ngxMasonryItem *ngFor="let swipeFile of swipeFiles" class="card-swipe-file" (click)="onSwipeFileClick(swipeFile)">
    <div *ngIf="swipeFile.imageUrl" class="linear-background" [ngStyle]="{'width': '300px', 'height': 300 * (swipeFile.imageHeight / swipeFile.imageWidth) + 'px'}" > 
      <img mat-card-image [src]="swipeFile?.imageUrl" alt="image">
    </div>
    
    <mat-card-content>
      <div class="card-title">{{swipeFile?.name}}</div>
      <div class="card-content">{{swipeFile?.description}}</div>
    </mat-card-content>
  </mat-card>
</ngx-masonry>
```

I am building with --source-map=false for both dev and prod otherwise I get a compilation error.

**Comment by wynfred** [comment]
The issue should be fixed in the latest angular. What version are you using?

**Comment by madmacc** [comment]
"ngx-masonry": "^1.1.4", (The current latest)
"@angular/animations": "~8.2.5",
"@angular/core": "~8.2.5"

**Comment by wynfred** [comment]
OK, could you please reproduce it in a repo or stackblitz? I'll take a look at it.

**Comment by madmacc** [comment]
Sure.  I could not reproduce on stackblitz as it needs to be built with --prod.
Its my first time adding something to github so let me know if there are any issues.
https://github.com/madmacc/ngxMasonryExample

To reproduce:
ngserve --prod or ngbuild --prod

When the page is first loaded, the refresh button or browser refresh button is clicked it should perform the double animation.

**Comment by wynfred** [comment]
Seems like although pure_getter was removed, the animation issue is still there. I'm closing this and will reopen the previous issue.
As workaround, you could disable the animation in masonry and add your own angular animation.

**Comment by rozzs74** [comment]
Hi, I am experiencing this issue. My angular version is 6.0.2
