### ISSUE TITLE
card updated change the order

### ISSUE THREAD

**Issue by etsraphael** [wynfred/ngx-masonry#28]
I my situation I have two problems: 

1. In my card I have a textarea, when the textarea is recized the disposition of the masonry not changing. Do we have a solution for that ? 

2. And when my card get an update. Like a changement of the number of likes, the card it's directly repositioned in the masonry

Thank you if you have a way the skip the problems of cards updated

**Comment by wynfred** [comment]
1. You need to find a way to listen to the resize event of the element, and then call the `layout()` function of masonry.
2. Not sure what the issue is. If you can reproduce it on stackblitz I can take a look at it.

**Comment by wynfred** [comment]
Feel free to reopen if you have repro steps
