### ISSUE TITLE
percentPosition: true

### ISSUE THREAD

**Issue by kouxiangxinfu** [wynfred/ngx-masonry#29]
hai, When I use the option"option = {percentposition: true}" and the height and width of the picture are scaled equally, the layout of the picture in the horizontal direction is right, but the layout in the vertical direction is wrong.
![A18BEF76-8177-47d6-A751-E9F9FB118E8A](https://user-images.githubusercontent.com/19645566/71455380-a6e59a00-27cf-11ea-9b7c-c3b74892b208.png)
![8F6E41FF-5E47-4128-8E84-9FEEF758CC9F](https://user-images.githubusercontent.com/19645566/71455383-a9e08a80-27cf-11ea-9200-511c97542292.png)

**Comment by wynfred** [comment]
Hi, could you make sure that you used the right container as masonry item? Not sure what the problem is here. If you can provide a repro I can take a look at it.

**Comment by wynfred** [comment]
Feel free to reopen if you have repro steps
