### ISSUE TITLE
item always added to end with filter

### ISSUE THREAD

**Issue by mjheller** [wynfred/ngx-masonry#3]
<ngxMasonryItem class="masonry-item" *ngFor="let item of items | orderBy: '-date'"> {{item}} </ngxMasonryItem>

After initial load if a new item is added it will always show at bottom. Need to refresh for it to be ordered right. Using Angular 6.

Functionality works right without ngx-masonry

**Comment by vanncho** [comment]
I'm facing the same issue and looking for a solution.

**Comment by keandfan** [comment]
> I'm facing the same issue and looking for a solution.

have you been solved it ? i have the same problem.

**Comment by jpekeene** [comment]
Best workaround for me was this:-
```
this.myItems = [];

setTimeout(()=> {
    this.myItems = this.allItems.filter((item) => item.value === this.filter)
})

```

So reset the array to empty then use a timeout to populate it after the fact. Seems there's no way of accessing the items in the masonry array using ViewChild so this was the best I could figure. Obviously a bit hacky but works.

**Comment by wynfred** [comment]
Try reload_items after the order of array is changed https://github.com/wynfred/ngx-masonry/issues/18#issuecomment-520551876
