### ISSUE TITLE
Type error 

### ISSUE THREAD

**Issue by rozzs74** [wynfred/ngx-masonry#30]
![error](https://user-images.githubusercontent.com/14355779/72948407-0085b800-3dc0-11ea-8708-09c679ffc79a.png)

**Comment by wynfred** [comment]
The screenshot isn't really useful here. If you can provide a repro I can take a look at it.

**Comment by rozzs74** [comment]
public remove(element: HTMLElement) {
    // Tell Masonry that a child element has been removed
    this._msnry.remove(element);

    // Layout items
    this.layout();
  }

**Comment by wynfred** [comment]
A new version that supports better image loading was released. I decided to not support imagesLoaded anymore. I would appreciate if you can help test the new version and report issues. Thank you!
