### ISSUE TITLE
FIX ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.     at NgxMasonryComponent.push../node_modules/ngx-masonry/fesm5/ngx-masonry.js.NgxMasonryComponent.add 

### ISSUE THREAD

**Issue by akropolis7** [wynfred/ngx-masonry#31]
You try to delete an element from the DOM tree, if the Dom tree does not have this element, the code falls into an error, this problem is manifested if we use the parameter [useImagesLoaded]= " true";

fesm2015 => ngx-masonry.js:
`if (this.useImagesLoaded) {
            imagesLoaded(element, function (instance) {
                _this._element.nativeElement.appendChild(element);
                // Tell Masonry that a child element has been added
                _this._msnry.appended(element);
                // layout if first item
                if (isFirstItem) {
                    _this.layout();
                }
            });
          safe(() => this._element.nativeElement.removeChild(element));
        }` 
change to:
`if (this.useImagesLoaded) {
            imagesLoaded(element, function (instance) {
                _this._element.nativeElement.appendChild(element);
                // Tell Masonry that a child element has been added
                _this._msnry.appended(element);
                // layout if first item
                if (isFirstItem) {
                    _this.layout();
                }
            });
          safe(() => this._element.nativeElement.removeChild(element));
        }
`

line `this._element.nativeElement.removeChild(element);` => `safe(() => this._element.nativeElement.removeChild(element));`

`
/**
 * A small dirty hack that safely implements the passed fn function.<br / >
 * Serves to get a property with a long chain method, where some part of the chain may be undefined.
 *
 * @example
 * if (safe (() = > this.foo[0].bar.isUseful)) { ...
 * // returns 'this.foo[0].bar.isUseful' or undefined, avoiding creating exceptions.
 *
 * @param fn - some simple functions, preferably lambda.
 * @returns {T | undefined}

 */
export function safe<T>(fn: () => T): T | undefined {
  try {
    return fn();
  } catch {
    return undefined;
  }
}
`
you can take `safe method` with my npm packege `npm install angular2-utilites` or `yarn add angular2-utilites`

**Comment by wynfred** [comment]
Hello, are you trying to destroy an item before it's loaded?

**Comment by akropolis7** [comment]
no, i youse 
```
readonly masonryOptions = {
    itemSelector: '.grid-item',
    columnWidth: '.grid-sizer',
    gutter: '.gutter-sizer',
    percentPosition: true,
    horizontalOrder: true,
};

<ngx-masonry [options]="masonryOptions" [useImagesLoaded]="true">
     <div class="grid-sizer"></div>
     <div class="gutter-sizer"></div>
     <div ngxMasonryItem class="grid-item">{{some Product}}</div>
</ngx-masonry>
```

First I am on the page with ads, then I go to the product page, and click the Back button in the browser => this error appears.

Other logic is missing, all out of the box

**Comment by wynfred** [comment]
A new version that supports better image loading was released. I decided to not support imagesLoaded anymore. I would appreciate if you can help test the new version and report issues. Thank you!

**Comment by akropolis7** [comment]
i test it, thank you

пн, 13 апр. 2020 г. в 10:33, wynfred <notifications@github.com>:
