### ISSUE TITLE
Update of array which is used for "ngFor" changes the order

### ISSUE THREAD

**Issue by kimurayu45z** [wynfred/ngx-masonry#32]
```html
<ng-container *ngIf="missionPostList$ | async as missionPostList">
            <ngx-masonry [options]="{ transitionDuration: '0s' }">
              <ng-container *ngFor="let missionPost of missionPostList$ | async; let i = index">
                <div ngxMasonryItem class="item">
                </div>
              </ng-container>
            </ngx-masonry>
        </ng-container>
```

`missionPostList$` is `any[]`.

Please image that `missionPostList$ | async` is
`[a, b, c, d]`

then, we execute some process which changes `b.prop`.

Of course, `missionPostList$ | async` will be updated as new value `[a, b, c, d]`

However, the order of view of `<div ngxMasonryItem class="item">` is as an order of `[a, c, d, b]`.
An element which of the property be changed go to the bottom of view.

Why?

**Comment by wynfred** [comment]
To update the order of the list, see - https://github.com/wynfred/ngx-masonry/issues/18#issuecomment-520551876

**Comment by wynfred** [comment]
Updated readme with instructions - https://github.com/wynfred/ngx-masonry#faq
