### ISSUE TITLE
Angular 9 compatibility.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [wynfred/ngx-masonry#33]
Hi,

I am using this package in Angular 9 project and I am getting the below error. Please let me know if the package is ready for Angular 9 Ivy.

```
 ERROR in node_modules/ngx-masonry/lib/ngx-masonry.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of StashModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-masonry) which declares NgxMasonryModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

Please let me know what can be done for Angular 9 projects.

**Comment by wynfred** [comment]
what version of this library are you using? and could you try deleting node_modules and re install?

**Comment by VigneshVaidyanathan** [comment]
I am sorry for the late reply. I installed the latest version of the app 9.1.1 and it works like a charm now
