### ISSUE TITLE
Facing overlapping issue between cards

### ISSUE THREAD

**Issue by zeeshanshanif** [wynfred/ngx-masonry#35]
The overlapping issue will be resolved if using [useImagesLoaded]="true" in div tag. next to ngxMasonryItem but card order will be change on every time page refreshes is there any way to resolve image overlapping issue without [useImagesLoaded]="true" and my card order will be not changed?

![image](https://user-images.githubusercontent.com/8614129/80358948-96851f00-8896-11ea-9578-fcf9afe29951.png)

I have also updated ng-masonry to v9 and not use [useImagesLoaded]="true" but still facing overlapping issue.

**Comment by FelipeSanchezCalzada** [comment]
Same question here

**Comment by wynfred** [comment]
When there are images, they are loaded asynchronously by browser and appended to masonry. You can implement your own synchronous item, or try https://github.com/wynfred/ngx-masonry#faq to restore the order after all items are loaded.

If you have overlapping issue with V9, try clean your masonry option and see if any of your setting is causing the issue. If you can provide an online repro I can also take a look.

**Comment by zeeshanshanif** [comment]
> When there are images, they are loaded asynchronously by browser and appended to masonry. You can implement your own synchronous item, or try https://github.com/wynfred/ngx-masonry#faq to restore the order after all items are loaded.
> 
> If you have overlapping issue with V9, try clean your masonry option and see if any of your setting is causing the issue. If you can provide an online repro I can also take a look.

I have tried  https://github.com/wynfred/ngx-masonry#faq  but its just for first

**Comment by stolenhead** [comment]
have same issue :(

**Comment by wynfred** [comment]
feel free to reopen if you could repro it on stackblitz
