### ISSUE TITLE
Misplaced masonry items

### ISSUE THREAD

**Issue by xigolle** [wynfred/ngx-masonry#36]
When i try to use it I get the following problem:
![image](https://user-images.githubusercontent.com/4833546/80985189-298dfe00-8e2f-11ea-89fa-06fec04cb530.png)

It never wants to start at the beginning of the div with drawing. 
The gap gets bigger with the amount of items I add.
This is how my template looks like:
![image](https://user-images.githubusercontent.com/4833546/80985288-4f1b0780-8e2f-11ea-8887-b8dbe1433bed.png)
And these are the options I am currently using:
![image](https://user-images.githubusercontent.com/4833546/80985314-57734280-8e2f-11ea-9c47-64c8dc32d8aa.png)

I am not sure if I did something wrong or this is a problem of the package.
Would love to give extra information if needed.

**Comment by wynfred** [comment]
It's difficult to identify the problem here, but seems like you would need to try these sizing related options - https://masonry.desandro.com/options.html#recommended

**Comment by xigolle** [comment]
@wynfred Tried setting all these settings but none seem to work and some made it even worse. 
For now I am going for another approach for creating a masonry layout. 
If you still want to investigate this issue for future people with the same problem I sure want to help.
But for now I will close the issue. 
Reopen/let me know if you still want to work on it.

**Comment by wynfred** [comment]
Hi, if you could provide a repro project I would like to investigate the issue.

**Comment by zeroregard** [comment]
I'm getting the same issue. It seems for me the fix is adding `position: absolute !important` to masonry items. If not, it's set to fixed for some reason.
