### ISSUE TITLE
Can't be part of an Angular 9 SSR deployment because of 'window' access in masonry.js

### ISSUE THREAD

**Issue by jasonburrows** [wynfred/ngx-masonry#37]
It seems that this can't be part of an angular 9 SSR deployment because `isPlatformBrowser` is not being checked on calls to masonry.js.

This was not a problem in Angular 8 but something in Angular 9 seems to have caused this problem with external references to 'window'.

Note that even if in my local project I wrap all references in `isPlatformBrowser` checks, the incompatible modules are still loaded and this results in the following error:

```
>front@2.30.0 servedev:ssr /Users/me/Development/front
> NODE_ENV=dev node dist/server/main

/Users/me/Development/front/dist/server/main.js:200603
}( window, function factory( Outlayer, getSize ) {
   ^

ReferenceError: window is not defined
    at Object../node_modules/masonry-layout/masonry.js (/Users/me/Development/front/dist/server/main.js:200603:4)
    at __webpack_require__ (/Users/me/Development/front/dist/server/main.js:20:30)
    at Module../node_modules/ngx-masonry/__ivy_ngcc__/fesm2015/ngx-masonry.js (/Users/me/Development/front/dist/server/main.js:225304:72)
```

**Comment by wynfred** [comment]
Seems like it's in masonry-layout itself - https://github.com/desandro/masonry/blob/master/masonry.js#L9
Not sure what I can do about it. If it works in V8 but not in V9 you could consider open an issue for Angular.

**Comment by jasonburrows** [comment]
From what I can tell the issue is that the last angular based module in the chain has to use isPlatformBrowser to disable calls to external non-angular libraries that might use browser functions.

So while I 100% agree that I think this is not really a good solution from the Angular team, and I do have a bug filed with them as well (https://github.com/angular/universal/issues/1675), it seems like their expectation is that third parties providing angular modules do browser check guards against any non-angular js they might use.

So - if you are willing - we could check if that fixes it by you putting all of the component.ts calls out to masonry-layout into an isPlatformBrowser check, and use an ng-container block in your templates to only render if they are in a browser.  I understand that all of the features of your library will then be disabled, but at least it will be deployable to an Angular 9 SSR application and work correctly in the browser.

If this change is made and it does NOT fix the problem, then it means there is literally no way to use any third party module that calls non-angular js using browser functions and the functionality of isPlatformBrowser is essentially useless (as, from my perspective as a consumer, it fails as soon as the module is loaded regardless of if my code even uses ANY feature in the library so isPlatformBrowser never even has a chance to work correctly).

**Comment by wynfred** [comment]
The necessary checks are already there https://github.com/wynfred/ngx-masonry/blob/master/src/lib/ngx-masonry.component.ts#L47 .

So unfortunately this needs to be fixed on Angular side unless I misunderstand something.

**Comment by jasonburrows** [comment]
Right - thanks so much for pointing that out to me.  I've updated my bug at angular-universal with this information.

Hopefully they will take a look at it!

**Comment by wynfred** [comment]
Hopefully :)

**Comment by wynfred** [comment]
just FYI https://github.com/desandro/masonry/pull/1121

**Comment by jasonburrows** [comment]
Hey so the angular team finally got back to me and they suggest (kind of amazingly) that `isPlatformBrowser` is not sufficient on its own and they pointed back at this library as the source of the issue (specifically the use of a lazy require in place of import).

Here's the comment about ngx-masonry specifically:

https://github.com/angular/universal/issues/1675#issuecomment-690971575


...I personally feel they should fix things on their side but it doesn't look like that's in the cards.
