### ISSUE TITLE
Order of items not working

### ISSUE THREAD

**Issue by ifumi** [wynfred/ngx-masonry#38]
I have seen multiple closed issues adressing this problem, but none of them seems to provide a solution. Is the "horizontalOrder" option broken?

I am loading an array of image objects from my database and using it to display the images and some other information. 

HTML of the component:

```
<ngx-masonry [options]="masonryOptions">
    <div ngxMasonryItem class="wall-item" *ngFor="let image of images">
        <app-image-wall-post [username]="image.name" [message]="image.message" [imagePath]="image.path" [timestamp]="image.timestamp"></app-image-wall-post>
    </div>
</ngx-masonry>
```
The **app-image-wall-post** component contains a material card with the image in it.

TS of the component:
```
export class ImageWallComponent implements OnInit {
  images: ImageEntry[];

  public masonryOptions: NgxMasonryOptions = {
    horizontalOrder: true,
    originTop: true,
    originLeft: true,
    itemSelector: '.wall-item',
  };

  constructor(private wallService: WallService, private router: Router, private eventService:EventService) { }

  ngOnInit(): void {
    this.wallService.initImageStream();

    this.wallService.images.subscribe(newImages => {
      this.images = newImages.sort((a,b) => (a.timestamp > b.timestamp) ? -1 : ((b.timestamp > a.timestamp) ? 1 : 0));

      this.images.forEach(image => {
        console.log(new Date(image.timestamp) + ", " + image.name)
      })
    });
  }
}
```

The sort function in the subscribe callback makes sure that the images are sorted by their upload-timestamp. When checking the console output of the images array, the sorting seems fine. However, the masonry order is somehow random. Each time I refresh the page, the order changes. 

Here is also a screenshot of the console output where you can see the properly sorted array, and the images. which are not ordered properly (see the date information on the card): 
![image](https://user-images.githubusercontent.com/22797603/81690627-d84bc300-945b-11ea-99d3-b086add7a807.png)

Why is that, and what am I doing wrong? When I use a normal flexbox layout, the order is correct.

**Comment by wynfred** [comment]
https://github.com/wynfred/ngx-masonry#faq

Images are downloaded asynchronously so the order is not guaranteed. I have plan to support synchronous loading but it's gonna take time.

**Comment by ifumi** [comment]
Is there a way to implement synchronous loading of the images myself? So basically wait for each image in the array to be loaded before setting the next image?

**Comment by wynfred** [comment]
@ifumi right, put the items to an array like `pendingItems`, and use an event from image item
`<img src="{{imageUrl}}" (load)="loaded.emit()" (error)="loaded.emit()">`.
When your masonry component gets the `loaded` event  do 
`      this.cardItems.push(this.pendingItems.shift());`

**Comment by ifumi** [comment]
Great! Thank you for making that clear for me. I got it working that way and it also looks super smooth now with the images loading one by one!

**Comment by ifumi** [comment]
But this means, there is no way to add items to the beginning of the masonry without reloading the whole view, right?

**Comment by wynfred** [comment]
There is a `prepend` function but no `insert`, so you can add items to the beginning but not in the middle. https://masonry.desandro.com/methods.html#prepended

**Comment by ifumi** [comment]
Could you give a short example on how to accomplish that? There is no prepend on NgxMasonryComponent, only add.

**Comment by wynfred** [comment]
you can access the masonry instance and call any native functions you need https://github.com/wynfred/ngx-masonry/blob/master/src/lib/ngx-masonry.component.ts#L35

change this to prepended https://github.com/wynfred/ngx-masonry/blob/master/src/lib/ngx-masonry.component.ts#L107

**Comment by ifumi** [comment]
Ok, but how would I do this in my case with a new "app-image-wall-post" component?
To clarify my problem: Im getting images from a database when a user uploads a new image, and I always want to display the newest image at the top -> e.g. add a new app-wall-post-component with the corresponding image to the beginning. How would I add this component dynamically from my code to the masonry?

Sorry if my questions are silly, but I'm quite new to web/angular development.

**Comment by wynfred** [comment]
Hi, try the new release with option `prepend`!
`<div ngxMasonryItem [prepend]="image.prepend" *ngFor="let image of masonryImages">`

**Comment by yingwei1025** [comment]
Hi wynfred, i also face this not in order problem when card div have to load the image, without image is work fine

i using prepend but it seem no work, am I use it incorrect?


```
<ngx-masonry [options]="masonryOptions">
<mat-card ngxMasonryItem [prepend]="post.prepend" *ngFor="let post of eventPostList">
<img mat-card-image src="{{ post.cardImgUrl }}" />
<mat-card-content fxLayout="column">
<span>{{ post.postTitle }}</span>
<span>Post : {{ post.postDate }}</span>
<p align="justify">{{ post.postDesc }}</p>
</mat-card-content>
</mat-card>
</ngx-masonry>
```

**Comment by wynfred** [comment]
HI @yingwei1025 , prepend doesn't help get items ordered. You could read the first 3 comments about how to load an ordered list. LMK if you have any questions.

**Comment by yingwei1025** [comment]
Hi wynfred, I try to apply the solution u provide in 3rd comment to my code but not sure why it no work

my html

```
<ngx-masonry [options]="masonryOptions">
   <mat-card ngxMasonryItem *ngFor="let post of cardItems" class="grid-item">
     <img mat-card-image src="{{ post.imgURL }}" (load)="loaded()" (error)="loaded()"/>
     <span>{{ post.title}}</span>
  </mat-card>
</ngx-masonry>
```

my ts

```
export class NewComponent implements OnInit {
    cardItems: any[];
    pendingItems: any[];
    masonryOptions: NgxMasonryOptions = {
        horizontalOrder: true,
        itemSelector: '.grid-item',
    };

    constructor() {}

    ngOnInit() {
        this.getTestList();
    }

    public geTestList() {
        this.pendingItems= [{
                imgURL: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
                title: 'Post 1',
            },
            {
                imgURL: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
                title: 'Post 2',
            },
            {
                imgURL: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
                title: 'Post 3',
            }
        ]
    }

    public loaded() {
        this.cardItems.push(this.pendingItems.shift());
    }

}
```

**Comment by wynfred** [comment]
@yingwei1025 seems like you didn't push the first item to cardItems?

**Comment by yingwei1025** [comment]
Hi @wynfred , based on your solution `this.cardItems.push(this.pendingItems.shift())`; means that you push the first item to cardItems when image load ?  
But I not sure why `console.log(this.pendingItems.shift())` is empty means that it also push empty to cardItems

**Comment by wynfred** [comment]
@yingwei1025 yes, but you didn't call it in onInit. You need to either initialize the cardItems with one item or call `loaded` when it's initialized.
