### ISSUE TITLE
strange behaviors of masonry grid

### ISSUE THREAD

**Issue by webcat12345** [wynfred/ngx-masonry#39]
Hello!

I would like to report some strange behaviors of masonry grid. Also I would contribute on the library if you are okay with this.

- Sometimes grid gets lost its column count to 1 and never get recovered until I refresh the page
https://drive.google.com/open?id=15m5UkzDATY_GLsPpZ0_Zw8IYOEc-ZD-4
- Sometimes items are overlapped. They are not being displayed. It only happens on the first column
https://drive.google.com/file/d/1umLm6pacTwylzr2GWomrHH6zdTkl0LBo/view

Here goes my implementation

```
<ngx-masonry class="my-50" [options]="{gutter: gutter}" (layoutComplete)="layoutCompleted($event)">
  <div ngxMasonryItem class="masonry-item" *ngFor="let idea of ideas"
    [style.width]="cardWidth"
    [style.margin-bottom.px]="gutter">
    <job-hub-idea-board-card [editable]="editable"
                             [selectable]="selectable"
                             [clickable]="clickable"
                             [idea]="idea"
                             [isCustomer]="isCustomer"
                             (view)="view($event)"
                             (edit)="edit.emit($event)"
                             (delete)="delete.emit($event)"></job-hub-idea-board-card>
  </div>
</ngx-masonry>
<p class="d-flex align-items-center justify-content-center text-primary" *ngIf="hasPending">Loading
  {{ ideas.length > loaded ? ideas.length - loaded : loaded - ideas.length }} more images...
  <span class="d-inline-block ml-10 px-10 py-10 position-relative"><job-hub-spinner diameter="20"></job-hub-spinner></span>
</p>
```
```
export class IdeaBoardComponent implements OnInit {

  @Input() ideas: Idea[] = [];
  @Input() gutter = 20;
  @Input() col = 4;
  @ViewChild(NgxMasonryComponent) masonry: NgxMasonryComponent;

  loaded = 0;
  cardWidth;

  get hasPending(): boolean {
    return this.ideas.length > 0 && Boolean(this.loaded < this.ideas.length);
  }

  constructor(
    private sanitizer: DomSanitizer
  ) { }

  ngOnInit(): void {
    this.cardWidth = this.sanitizer.bypassSecurityTrustStyle(`calc((100% - ${(this.col - 1) * this.gutter}px) / ${this.col}`);
  }

  layoutCompleted(e) {
    if (this.loaded > this.ideas.length) {
      this.loaded = this.ideas.length;
      return;
    }
    if (e && e.length === 1) {
      this.loaded++;
    }
  }

  reset() {
    this.masonry.reloadItems();
  }
}
```

**Comment by webcat12345** [comment]
That bug 2, my guess is it's happening when I change `ideas` (list of items) even there are some pending images to be loaded.

**Comment by wynfred** [comment]
Not sure about 1, did you try to call `layout()` after you switch to another category? If you could share a simple repro project, I'll try if I can find what the issue is. One other suggestion I have is try destroy the masonry before you want to reload it completely.
For 2, before the images are loaded they are invisible with opacity 0. If they are clickable, you need to use your own CSS to hide them, and also make sure they are destroyed properly.

**Comment by webcat12345** [comment]
That makes sense your comment on issue 2. I can see opacity 0 div is there. But I can't find the best approach to disable click event for all of those opacity 0 divs. Do you have any guidance to give me? I don't see any additional classes added to un-aligned elements (those opacity 0 elements)...

Issue 1, I will try to call `layout()` function from my side, I will come back after some tries.
Thank you!

**Comment by webcat12345** [comment]
By calling the `layout()` function on category change event, I was able to figure out that issue 1. Not that perfect but it's working.

So, sometime, very barely column shows as 1. But if I change category it's getting recovered because I am calling the `layout()` function. So I would say issue has been resolved. Just trying to find out best way to handle issue 2, please let me know if you have any hint. Thank you!

**Comment by wynfred** [comment]
You can use the show/hide animation to set z-index to the items. When I work on the next release I'll make it default as well.

**Comment by webcat12345** [comment]
It works as charm!!! Legendary!
