### ISSUE TITLE
Transition resizing

### ISSUE THREAD

**Issue by Marius-Romanus** [wynfred/ngx-masonry#40]
Great job! Is it possible to put a transition back when reordering the items when resizing the screen, as in previous versions? sorry for my english translation.

**Comment by wynfred** [comment]
There are some performance concerns so the auto resizing was removed. You can implement this in an "angular" way by subscribing to ViewportRuler and call `layout()` - https://material.angular.io/cdk/scrolling/overview#viewportruler

**Comment by Marius-Romanus** [comment]
Hi, actually I had that question solved with `@HostListener('window:resize', ['$event'])` (I don't know which is better), but I have discovered that I simply needed the css "transition" rule for don't be so abrupt and be a smooth transition, thank you very much.

**Comment by wynfred** [comment]
glad you figured it out. window:resize would work but I recommend viewportRuler because it supports "refresh rate"
