### ISSUE TITLE
bug: sometimes grid column goes into one

### ISSUE THREAD

**Issue by webcat12345** [wynfred/ngx-masonry#41]
Hello!

Sorry again, I am opening this issue again, that 1 grid issue getting more buggy. We are seeing this problem so frequently, I would like to know source of this problem and I hope to help you to figure out this together. 

- Sometimes grid gets lost its column count to 1 and never get recovered until I refresh the page
https://drive.google.com/open?id=15m5UkzDATY_GLsPpZ0_Zw8IYOEc-ZD-4

Here goes my implementation

```
<ngx-masonry class="my-50" [options]="{gutter: gutter}" (layoutComplete)="layoutCompleted($event)">
  <div ngxMasonryItem class="masonry-item" *ngFor="let idea of ideas"
    [style.width]="cardWidth"
    [style.margin-bottom.px]="gutter">
    <job-hub-idea-board-card [editable]="editable"
                             [selectable]="selectable"
                             [clickable]="clickable"
                             [idea]="idea"
                             [isCustomer]="isCustomer"
                             (view)="view($event)"
                             (edit)="edit.emit($event)"
                             (delete)="delete.emit($event)"></job-hub-idea-board-card>
  </div>
</ngx-masonry>
<p class="d-flex align-items-center justify-content-center text-primary" *ngIf="hasPending">Loading
  {{ ideas.length > loaded ? ideas.length - loaded : loaded - ideas.length }} more images...
  <span class="d-inline-block ml-10 px-10 py-10 position-relative"><job-hub-spinner diameter="20"></job-hub-spinner></span>
</p>
```
```
export class IdeaBoardComponent implements OnInit {

  @Input() ideas: Idea[] = [];
  @Input() gutter = 20;
  @Input() col = 4;
  @ViewChild(NgxMasonryComponent) masonry: NgxMasonryComponent;

  loaded = 0;
  cardWidth;

  get hasPending(): boolean {
    return this.ideas.length > 0 && Boolean(this.loaded < this.ideas.length);
  }

  constructor(
    private sanitizer: DomSanitizer
  ) { }

  ngOnInit(): void {
    this.cardWidth = this.sanitizer.bypassSecurityTrustStyle(`calc((100% - ${(this.col - 1) * this.gutter}px) / ${this.col}`);
  }

  layoutCompleted(e) {
    if (this.loaded > this.ideas.length) {
      this.loaded = this.ideas.length;
      return;
    }
    if (e && e.length === 1) {
      this.loaded++;
    }
  }

  reset() {
    this.masonry.reloadItems();
  }
}
```

**Comment by webcat12345** [comment]
When I change filter, sometimes it gets to 1 column but if I refresh or change filter again, it goes to correct. But customers complaining about this.

**Comment by wynfred** [comment]
after you change the input array, did you call `reloadItems()` and then `layout()`?

**Comment by webcat12345** [comment]
When I call `reloadItems()` and `layout()` after changing the input array, I get these incorrect spacings around images. Not all time, but some times.

![image](https://user-images.githubusercontent.com/19761422/83051596-31853a80-a089-11ea-8cad-4f6ca33b8541.png)

**Comment by webcat12345** [comment]
Actually calling those two functions is maybe resolving that 1 column issue but grid is completely messy. I am trying some other methods on it.

**Comment by wynfred** [comment]
the native masonry functions and options may help - https://masonry.desandro.com/options.html

If you can put a simplified version on stackblitz I could help you debug it.
