### ISSUE TITLE
Error: No provider for AnimationBuilder

### ISSUE THREAD

**Issue by mrhieu** [wynfred/ngx-masonry#44]
I don't see anyone encountering this issue so not sure what I've done wrong.
I'm using ngx-masonry with Ionic 5, Angular 9.1.5. 
Earlier I got "missing @angular/animations" error and already install this dependency.

Thanks for the great work btw

<img width="808" alt="Screenshot 2020-06-03 00 44 46" src="https://user-images.githubusercontent.com/1593560/83546573-7569bb00-a533-11ea-83eb-0b0b634c2ff2.png">

**Comment by wynfred** [comment]
HI, could you make sure you correctly setup the angular animation - https://angular.io/guide/animations#getting-started

**Comment by mrhieu** [comment]
You are right, it works after that setup. Thank you. I'm closing this issue.
