### ISSUE TITLE
Grid doesn't always stay at top of page

### ISSUE THREAD

**Issue by shinkhouse** [wynfred/ngx-masonry#47]
Hey there,

I'm having some issues with the grid not staying at top of page. It's pretty random really and I'm not sure what settings I need to fix it. I've attached some screenshots for examples. I'm basically trying to get the pictures lined up with a 5px space between the toolbar and first row of pictures.

<img width="1640" alt="Screen Shot 2020-06-27 at 3 06 49 PM" src="https://user-images.githubusercontent.com/12039637/85931259-aa460500-b888-11ea-90e2-825607b14c92.png">
<img width="1640" alt="Screen Shot 2020-06-27 at 3 07 59 PM" src="https://user-images.githubusercontent.com/12039637/85931261-ad40f580-b888-11ea-93d0-15fec62141c5.png">
<img width="1640" alt="Screen Shot 2020-06-27 at 3 08 42 PM" src="https://user-images.githubusercontent.com/12039637/85931264-afa34f80-b888-11ea-96dc-b4b805d8fc55.png">
<img width="1640" alt="Screen Shot 2020-06-27 at 3 09 09 PM" src="https://user-images.githubusercontent.com/12039637/85931267-b16d1300-b888-11ea-815e-9b9e51baa9a9.png">
<img width="1640" alt="Screen Shot 2020-06-27 at 3 11 03 PM" src="https://user-images.githubusercontent.com/12039637/85931269-b631c700-b888-11ea-9250-f66cc64ac799.png">

Every once in awhile, it stays at the top... but most of the time not so much. 

Here is the repo for my project. You'll need a Giphy API key to get the grid working.

**Comment by shinkhouse** [comment]
I've discovered that if I comment out these two lines, the grid stays at the top. 
```
 this.masonry.reloadItems();
 this.masonry.layout();
```

**Comment by wynfred** [comment]
The two lines should only be used if the order of items changes. Feel free to reopen if there're other issues.
