### ISSUE TITLE
ngFor + a static element creates a gap in the grid

### ISSUE THREAD

**Issue by femtozer** [wynfred/ngx-masonry#50]
First, thank you for this amazing lib!
I'm having an issue with the following code snippet:
``` HTML
<ngx-masonry [options]="{ gutter: 15 }">
    <div ngxMasonryItem class="document masonry-item" *ngFor="let number of [0,1,2,3,4]">
        <div class="content">
            <div class="icon">
                <div class="triangle-topright"></div>
                <mat-icon>mic</mat-icon>
            </div>
        </div>
        <div class="label">Record {{number}}</div>
    </div>
    <div ngxMasonryItem class="document new masonry-item" (click)="recordReport">
        <div class="content">
            <div class="icon">
                <div class="triangle-topright"></div>
                <mat-icon>add</mat-icon>
            </div>
        </div>
        <div class="label">Upload a record</div>
    </div>
</ngx-masonry>
```
the combination of ngFor and a static element seems to create a gap in the grid:

![image](https://user-images.githubusercontent.com/13162553/87147735-7073f600-c2ad-11ea-9f28-aaf6de3158d0.png)

this is not the case without the static element:

![image](https://user-images.githubusercontent.com/13162553/87148296-71f1ee00-c2ae-11ea-90e0-da1e91287459.png)

Is it possible to use ngx-masonry this way? Otherwise, do you know a workaround?

Thanks!

**Comment by wynfred** [comment]
Hello, I'm not sure what's the root cause here but a workaround would be using ngif to display the extra item after the list are loaded. Or add the item to the array with a "type" property and then ngswitch

**Comment by femtozer** [comment]
Thanks! The ngIf solution works perfectly

**Comment by Xyaren** [comment]
I experience the same issue, but also try to preserve ordering with `[orderd]="true"`. 
This results in nothing being rendered at all...

**Comment by Xyaren** [comment]
So, debugging the code I observed the following:
The static element being added to masonry by itemLoaded even, if it already exists in masonry, because it was already there, when masonry initialized.
Maybe skipping
`this.masonryInstance.prepended(item.element.nativeElement);` or 
`.masonryInstance.appended(item.element.nativeElement);`

would fix it in that case?

**Comment by thesleort** [comment]
I have the same issue. @Xyaren skipping these will fix that issue, but I am not sure whether it will prevent new dynamic content from being loaded? Haven't looked too much on the code yet, but I did try and remove these lines, which fixed it for me, however, currently I only use static elements (hardcoded in the source HTML).

**Comment by thesleort** [comment]
For me it appears that static elements are added immediately to the list of items, but then after that they are spotted as new items, which means that every static element will add a new empty gap.
In my case I have 5 static elements, which means that the total count of items in the masonry is 10.
