### ISSUE TITLE
blog.module.ts depends on 'ngx-masonry'. CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by celvin** [wynfred/ngx-masonry#54]
Recently upgraded to Angular 10 and getting this error messages:

blog.module.ts depends on 'ngx-masonry'. CommonJS or AMD dependencies can cause optimization bailouts

ngx-masonry.js depends on 'masonry-layout'. CommonJS or AMD dependencies can cause optimization bailouts.

My tsconfig.json
```
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../out-tsc/e2e",
    "module": "ES2020",
    "target": "es2018",
    "types": [
      "jasmine",
      "jasminewd2",
      "node"
    ]
  }
}
```

**Comment by umrtariq** [comment]
Facing the same issue in angular 9 as well.

**Comment by wynfred** [comment]
related to https://github.com/angular/angular-cli/issues/18025

**Comment by wynfred** [comment]
To remove the warning: https://github.com/wynfred/ngx-masonry-demo/commit/a9fe783325f25d7dcf2c69cb0544a7963d3bd09f
