### ISSUE TITLE
Need help with showing items in a responsive manner

### ISSUE THREAD

**Issue by AkshayRaut1321** [wynfred/ngx-masonry#56]
Hi Wynfred

I checked the demo repository for this https://ngx-masonry-demo.herokuapp.com/

But when I cloned and ran this repo, the end result is not responsive. Unlike the live demo website, it doesn't add or reduce columns as per the width.

Can you please help ? I need an code example for showing items in responsive way.

**Comment by wynfred** [comment]
Hi, you just need to call the `layout()` function when the size of masonry/window changes.

One way to listen to the change of window size is to use angular CDK. https://material.angular.io/cdk/layout/overview
