### ISSUE TITLE
Auto adjust number of columns

### ISSUE THREAD

**Issue by clavinovahan** [wynfred/ngx-masonry#59]
It looks like by default, it shows only 3 columns of items. How to make it auto adjust number of columns based on screen size?

**Comment by wynfred** [comment]
Hi, there's no default number of columns. It depends on the width of parent/item. So what you need is dynamic item width and there are many ways of doing that. For example you can check
https://material.angular.io/cdk/layout/overview
https://github.com/angular/flex-layout
