### ISSUE TITLE
masonry grid sometimes displays the content vertically rather than horizontally

### ISSUE THREAD

**Issue by bijal1stop** [wynfred/ngx-masonry#60]
Version:- "ngx-masonry": "^10.0.5",

We have integrated the ngx-masonry package in our angular app. It's working quite nicely but we are facing one uncertain issue as mentioned below.

1. We have set the Masonry options as below.
    NgxMasonryOptions {
	gutter: 16,
	fitWidth: true,
	animations: {},
	horizontalOrder: true
    }
2. We have specified the horizontalOrder property to true which works perfectly to maintain the content order. The issue that we are facing is, sometimes this plugin automatically change the content layout and it shows vertically rather than showing horizontally. Find references below.

Below is the perfect horizontal layout that we need to display.
![image](https://user-images.githubusercontent.com/60265852/96685245-77290380-139a-11eb-971b-7d8eac019567.png)

Below is the issue we are facing randomly with the same NgxMasonryOptions.
![image](https://user-images.githubusercontent.com/60265852/96685274-80b26b80-139a-11eb-8f56-eb559ff738de.png)

We tried to resolve this issue, but I guess the HTML structure and all other layout related stuff has nothing to do with this issue.

Can you please look into this issue and let us know the resolution for the same so we can update it from our end accordingly.

Reference Code:-

HTML

```
<ngx-masonry [ordered]="true" [options]="getNgxMasonryOptions()">
    <div
      *ngFor="let viewModel of viewModels"
      ngxMasonryItem
      class="masonry-grid-item"
      [class.hovered]="hoveredItems.includes(viewModel._id)"
      (mouseenter)="addHoverStyle(viewModel)"
      (mouseleave)="removeHoverStyle(viewModel)"
      (click)="itemClick.emit({event: $event, viewModel: viewModel})">
</div>
  </ngx-masonry>
```

Component.ts

```
getNgxMasonryOptions(): NgxMasonryOptions {
    return {
      gutter: 16,
      fitWidth: true,
      animations: {},
      horizontalOrder: true
    };
  }
```

Thanks for providing such a beautiful package :-)

**Comment by wynfred** [comment]
It's difficult to identify the root cause here, but the first thing you could try is the column width option. Create a new invisible element with the width you need and add the selector to the option. Let me know if it works.
https://masonry.desandro.com/options.html#columnwidth

**Comment by bijal1stop** [comment]
sure, let me try to set column width and get back to you.

**Comment by bijal1stop** [comment]
@wynfred thanks for your prompt response. I have applied the columnWidth property and it seems to be working fine now. Really appreciated!
