### ISSUE TITLE
Item overlaps until window resize

### ISSUE THREAD

**Issue by konstantinosftw** [wynfred/ngx-masonry#61]
I load 10 images with ngFor and I get a single image overlapping, which gets correctly positioned after I resize the window. This type of thing used to get fixed with `[useImagesLoaded]="true"`, but this property not supported anymore.

Any ideas how to handle this?

[Related stackoverflow question (older version)](https://stackoverflow.com/questions/55499009/masonry-overlay-in-angular-7)

**Comment by wynfred** [comment]
What version are you using, and do you mean only one image in the array didn't get positioned correctly?

**Comment by konstantinosftw** [comment]
@wynfred thank you for the reply.

Exactly, I mean that a single image is being overlapped by the one below it and it is actually always in the same position - the topmost right of my 2 column layout. No matter the image file loaded in this position.

On desktop, where I load 3 columns, both the top-middle and top-right are getting overlapped by the below images. That is, until I resize the window width (does not happen when I resize the height) and everything falls into place.

My versions are:
` "ngx-masonry": "^10.0.5"`
`"masonry-layout": "^4.2.2"`
`"@angular/cdk": "^9.2.4"`

**Comment by wynfred** [comment]
Could you check the size of the overlap? Does it match something in the image card?

It seems like something changed its size after the calculation is done. And could you provide a screenshot?

**Comment by konstantinosftw** [comment]
Good idea. It seems that the only significant variable is the `min-height` of the img elements. The bottom images that overlap the ones above them are treating the top ones as though they have the `min-height` - although they are taller. When I load images shorter than the `min-height` on those positions, they are not being overlapped. 

But this miscalculation happens only for the top-right corner of the masonry layout, all the other heights are being respected. And I load all the images with the same ngFor* function, I don't treat any images specially. 

Here is a screenshot. This is the desktop 3-column layout. The two images that are being overlapped have different heights with each other. They are being overlapped as though they both had `min-height`.

P.S. The image legend on the bottom of the images does not match with the overlap, I tested it.

edit: these are my settings
``` 
public masonryOptions: NgxMasonryOptions = {
    gutter: 10,
    itemSelector: "#item",
    columnWidth: "#item",
    horizontalOrder: true,
    fitWidth: true,
    percentPosition: true,
    animations: {}
  };
```

![image](https://user-images.githubusercontent.com/23435302/97349536-42381780-1898-11eb-85f7-ab2987691df9.png)

**Comment by pimmesz** [comment]
I'm having a similar issue! Created two items with a margin-bottom of 24px. On initial load it overlaps over that margin. After resize it looks as intended.

![before](https://user-images.githubusercontent.com/7393354/97449299-cf7b7a80-1931-11eb-9c3f-4beb53c680e5.png)
![after](https://user-images.githubusercontent.com/7393354/97449303-d0141100-1931-11eb-9e8f-2d049d219d84.png)

**Comment by wynfred** [comment]
@konstantinosftw do you have any show/hide logic for the image? The lib will look for all <img> tags when an item is added, so if you have an ngif it may cause problem.

**Comment by wynfred** [comment]
@pimmesz I don't think it's related to the margin. Seems like the content(height) of the card changed after it's loaded.

**Comment by konstantinosftw** [comment]
@wynfred thanks for the feedback. I use just a simple ngFor, everything else is pretty much default - no conditionals or anything fancy at all.

I took some time and created a [Stackblitz example](https://stackblitz.com/edit/ngx-masonry-layout-issue?file=src/app/app.component.html). Please have a look. The top right image gets overlapped.

P.S. If you want to see the lower image snapping into place when resizing the viewport, open it as a mobile sized Responsive device on Chrome Dev Tools and drag the width a couple of pixels wider. Stackblitz's viewport is a bit odd when resizing and breaks the masorny.

P.S.2. I think it might have to do with `percentPosition: true` as this percentage CSS width is the only "calculation" I can think of during the rendering.

![image](https://user-images.githubusercontent.com/23435302/97894584-58802080-1d3b-11eb-8fd5-7de90da06e7d.png)

**Comment by wynfred** [comment]
Hi @konstantinosftw , the stackblitz project was really helpful!

The issue is you need to remove fitWidth because it doesn't work with element sizing.
https://masonry.desandro.com/options.html#fitwidth

**Comment by konstantinosftw** [comment]
@wynfred you are the best, I would have never noticed it. I tested it and you are correct, everything falls into place now that I removed `fitWidth: true`.

My issue is resolved, hope this also helps @pimmesz. 

Thanks again!

**Comment by medleyaaron9** [comment]
> Good idea. It seems that the only significant variable is the `min-height` of the img elements. The bottom images that overlap the ones above them are treating the top ones as though they have the `min-height` - although they are taller. When I load images shorter than the `min-height` on those positions, they are not being overlapped.
> 
> But this miscalculation happens only for the top-right corner of the masonry layout, all the other heights are being respected. And I load all the images with the same ngFor* function, I don't treat any images specially.
> 
> Here is a screenshot. This is the desktop 3-column layout. The two images that are being overlapped have different heights with each other. They are being overlapped as though they both had `min-height`.
> 
> P.S. The image legend on the bottom of the images does not match with the overlap, I tested it.
> 
> edit: these are my settings
> 
> ```
> public masonryOptions: NgxMasonryOptions = {
>     gutter: 10,
>     itemSelector: "#item",
>     columnWidth: "#item",
>     horizontalOrder: true,
>     fitWidth: true,
>     percentPosition: true,
>     animations: {}
>   };
> ```
> 
> ![image](https://user-images.githubusercontent.com/23435302/97349536-42381780-1898-11eb-85f7-ab2987691df9.png)





https://stylesheets.space/questions/three-images-intersecting-one-another
