### ISSUE TITLE
Warning: src\app\app.module.ts depends on 'ngx-masonry'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### ISSUE THREAD

**Issue by Neizan93** [wynfred/ngx-masonry#62]
Warning: src\app\app.module.ts depends on 'ngx-masonry'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by arjunasuresh3** [comment]
+1

**Comment by wynfred** [comment]
The core of this library is a JS lib and it's not updated for a while. You can use allowedCommonJsDependencies to disable the warning.
