### ISSUE TITLE
Latest version (v10) and Demo not working

### ISSUE THREAD

**Issue by aPinix** [wynfred/ngx-masonry#64]
Hi,

Just wanted to let you know that the latest demo isn't working. I was unable to get it to work on a project as well.

I took a picture from your link with the demo on [StackBlitz](https://stackblitz.com/edit/angular-ngx-masonry-filters?file=src%2Fapp%2Fapp.component.html).

<img width="1915" alt="CleanShot 2020-12-16 at 12 25 25@2x" src="https://user-images.githubusercontent.com/698523/102348624-108b2500-3f9a-11eb-9730-7b2d93eee580.png">

**Comment by vastellorde** [comment]
Add BrowserAnimationModule to AppModule
