### ISSUE TITLE
Screen is flickering while a new item added dynamically

### ISSUE THREAD

**Issue by bijal1stop** [wynfred/ngx-masonry#67]
Hi,

I have integrated this library and undoubtedly it works well! Recently I need to implement such a feature to add new items dynamically to the grid. Now, when I add a new item to the grid dynamically, the screen flickers for a few seconds (it goes blank for this time span), and then it is displaying the newly added item (along with other items).

As you can imagine, it won't be a really great user experience. So what I need to do is, whenever I add a new item to the grid dynamically, it should automatically add that new item without flickering the screen.

Version:- "ngx-masonry": "^10.0.5"

**Comment by wynfred** [comment]
Hi, it's difficult to identify the issue based on the description. Could you provide an online example or code and screenshots? Maybe some CSS or animation are causing the issue?
