### ISSUE TITLE
Angular 11 Support

### ISSUE THREAD

**Issue by daverickdunn** [wynfred/ngx-masonry#72]
NPM dependency error when using `"@angular/common": "~11.1.0"`, see below:

Note, this may in part be due to the NPM version, I believe the latest versions are stricter.

Node: 15.6.0
NPM: 7.4.0

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.0" from ngx-masonry@10.0.6
npm ERR! node_modules/ngx-masonry
npm ERR!   ngx-masonry@"*" from the root project
```

**Comment by wynfred** [comment]
updated the dependency :)
