### ISSUE TITLE
No animations for most recent angular versions?

### ISSUE THREAD

**Issue by HannesJo0139** [wynfred/ngx-masonry#73]
Sorry for asking here but I cannot find another place to do so. I try to implement ngx-masonry in my angular 11 project and everything works except for animations. If an element changes size or so, it just "jumps" but there is no animation at all. Therefore I tried to do a minimum setup based on your demo wynfred/ngx-masonry-demo. The hosted version is animated (Eg when triggering re-arrangement die to window resize) but seem to use angular8. So I cloned it to my local machine and there are also no animations. Do I miss somethin or are animations broken?

**Comment by wynfred** [comment]
Hi, the core masonry lib does support animation but it has many issues (you can try version v1.x). The animation implemented in this library is only for showing the items.

**Comment by HannesJo0139** [comment]
Thanks for your reply. So this is related to https://github.com/wynfred/ngx-masonry/issues/8? That was not clear to me. 
However, css transition property like
```
.masonry-item {
  transition: top 0.4s ease-in-out,  left 0.4s ease-in-out;
}
```
seems to work very well. Or do U see any problem with that? Maybe you could add a hint to the readme animation section on what animations work out of the box and what do not - or I may send a pull request adding that information?

**Comment by wynfred** [comment]
Yes, animation was re-implemented because of #8 

Looks good. Feel free to open a PR. Thanks!

**Comment by HannesJo0139** [comment]
See https://github.com/wynfred/ngx-masonry/pull/74

**Comment by wynfred** [comment]
:shipit:
