### ISSUE TITLE
Async data loading not supported ?

### ISSUE THREAD

**Issue by mmazloum** [wynfred/ngx-masonry#78]
I have a kind of portfolio page with async filters to display an artist portfolio. If I click on a tag, I call my server to fetch async data. The data arrive on my dom but masonry doesn't display them and their images properly.

If I fetch all my data before and just use filters without doing server side opérations, I find myself just like in the code provided in the masonry demo and everything works fine but it's a bit messy.

Any idea ?

**Comment by wynfred** [comment]
I'm not sure how you implemented it so it's difficult for me to guess what the issue is. But since you're clicking a tag and update the data, maybe you don't need to use the async pipe? If you can add an online repo that would be helpful.

**Comment by mmazloum** [comment]
@wynfred found a work arround not using async pipe, fetching all the data before activating my items (not best solution but enough for my project).

However thanks for your work this ngx-masonry is usefull ;-)

If I have time i'll get back to you with a fix.

**Comment by zeroregard** [comment]
Seconding this, you can test this with something like:
```
<ngx-masonry>
    <div ngxMasonryItem style="width:33%">
        static content
    </div>
     <div ngxMasonryItem style="width:33%">
        static content
    </div>
     <div ngxMasonryItem *ngIf="requestToApi$ | async as response" style="width:33%">
        {{ response }}
    </div>
</ngx-masonry>
```

The two first divs get a correct `left` css attribute while the async div gets: `right: -150vw;`

---

I'm reproducing this in a private corporate repository, but if I have time I'll see if I can make an open source reproduction repo. For now I'll have to make do as well with flexbox, but I would like to use this project in the future as it seems to be the only ivy-compatible masonry project that _almost_ works for my work repository :D

**Comment by wynfred** [comment]
I didn't find the issue with async pipe but I did fix another bug that may cause similar behavior. Try the latest release and let me know if it works. Thanks!

**Comment by mmazloum** [comment]
Thanks a lot, i've switched on another project but i'll keep you updated
