### ISSUE TITLE
Rendering twice on --prod version?

### ISSUE THREAD

**Issue by AhsanAyaz** [wynfred/ngx-masonry#8]
I'm having an issue with the grid items.
When running in dev env, it seems to work fine.
Also, building with --aot works fine.
But if I `serve` with `--prod` or build with `--prod`, the grid items are rendered twice :/

**Comment by ekstremedia** [comment]
I have the exact same issue! Did you ever figure this out?
Here is an example: [http://nesthus.no/ngxmasonry.mp4](http://nesthus.no/ngxmasonry.mp4)

**Comment by nsksaisaravana** [comment]
I am also having the same issue. Please fix this.

**Comment by inshaf** [comment]
im also having the same issue :(

**Comment by inshaf** [comment]
any solutions ?

**Comment by nsksaisaravana** [comment]
+1

**Comment by tempurai** [comment]
+1

**Comment by Murena7** [comment]
Hello, quick solution to fix twice rendering in --prod mode is: set in angular.json "buildOptimizer": false.
This solution does not greatly increase the size, and works well.

**Comment by kolomu** [comment]
pure_getters from build optimizer is probably causing this issue. See: https://github.com/angular/angular-cli/issues/11439 for more information or this link: https://github.com/angular/angular-cli/issues/12096

**Comment by wynfred** [comment]
The issue should be fixed. Feel free to reopen if it's not.

**Comment by nsksaisaravana** [comment]
@wynfred Thanks a lot, works like a charm. when are you going to upgrade to angular 7, 8, 9??

**Comment by wynfred** [comment]
@nsksaisaravana  The current version should work with v7 and v8. I think it should work with v9 and IVY as well, and I'll do more testing after the official v9 is released.

**Comment by madmacc** [comment]
The fix above by @Murena7 worked for me as an interim solution.

> Hello, quick solution to fix twice rendering in --prod mode is: set in angular.json "buildOptimizer": false.
> This solution does not greatly increase the size, and works well.

**Comment by wynfred** [comment]
@madmacc Just FYI, if you have an app in production, turning off buildOptimizer is not a good idea, unless you are fine with the change of bundle size.

**Comment by madmacc** [comment]
@wynfred  True.  I ended up using your other suggestion and turning off the animation and using my own angular animations.
```
masonryOptions: NgxMasonryOptions = {
    transitionDuration: '0'
  };
```

**Comment by flodaniel** [comment]
any update on this? does anybody have a suggestions to keep the animations and fix this? :)

**Comment by wynfred** [comment]
Hopefully this fixes the animation issue. I'd appreciate if you can help test the new release and report issues if there are.
https://github.com/wynfred/ngx-masonry#animations

**Comment by webcat12345** [comment]
@wynfred I really like your last update v9, that's amazing, just leaving this comment here, coz this is the only way to send you a message :) You are awesome :+1:

**Comment by wynfred** [comment]
@webcat12345 glad to hear that 😄

**Comment by rozzs74** [comment]
Any updates here?
