### ISSUE TITLE
fitWidth breaks resize

### ISSUE THREAD

**Issue by bkr32** [wynfred/ngx-masonry#85]
Version:latest.

using `fitWidth` causes the resize detection to break.

CSS:
```
ngx-masonry {
  margin: 0 60px;
}
```

HTML:
```
<div class="masonry">
  <ngx-masonry [options]="myOptions" >
    <div *ngFor='let item of new ngxMasonryItem >
      <app-card>
      </app-card>
    </div>
  </ngx-masonry>
</div>
```

```
  public myOptions: NgxMasonryOptions = {
    fitWidth: true,
    columnWidth:260,
    originLeft:true,
    horizontalOrder:true,
    gutter: 15,
  };
```

**Comment by wynfred** [comment]
Could you be more specific? fitWidth could be buggy, but I believe you can setup the layout without it. Maybe try fit the container with a margin?

**Comment by bkr32** [comment]
@wynfred resizing the window with fitWidth active doesn't resize the layout, however disabling it makes it work normally, in addition firing a layout reset on resize doesn't work either 
Will edit with the full code

EDIT:
code executed on `resizeobserver` however yields the same result
```
    this.masonry.reloadItems();
    this.masonry.layout();
```

**Comment by wynfred** [comment]
Hi, you have a fixed `columnWidth:260` so how would you expect the resizing to work? Your setup doesn't look good for responsive layout. I would suggest don't use fitWidth at all.

**Comment by bkr32** [comment]
Doesn't work even if columnWidth isn't present, card with is 260px as is

**Comment by wynfred** [comment]
Could you try to put it on stackblitz so I can take a look?

**Comment by bkr32** [comment]
@wynfred https://stackblitz.com/edit/angular-ivy-ceuzap?file=src/app/app.component.html

i have a layout quite similar to the above where the issue occurs

**Comment by wynfred** [comment]
Could you remind me why you have to use `fitWidth`? The layout works perfectly without it.

And with `fitWidth` enabled, it still works as expected. When you shrink the page, note that the page became scrollable. You need to shrink the container so it can layout the items again.

FYI - https://masonry.desandro.com/options.html#fitwidth

**Comment by bkr32** [comment]
why was this issue closed? nothing has been solved.

i'm using `fitWidth` for the very reason prescribed in the docs 
```
Sets the width of the container to fit the available number of columns, based the size of container's parent element. When enabled, you can center the container with CSS.
```

to center my masonry layout and items within the container, furthermore it does not wrap objects within the container as expected, the scrollable you are referring to is a horizontal scroll bar which is not ideal.

or is it simply not possible to have `fitWidth` working within a child container and expect it to resize based on screen size changes?
