### ISSUE TITLE
Unable to resolve dependency tree (i'm using Angular 11.x)

### ISSUE THREAD

**Issue by gkimpson** [wynfred/ngx-masonry#86]
I am running the command `npm install ngx-masonry masonry-layout --save` to install this but after the short period of time I get the following error in the terminal. Does this work with Angular 11.x ok - or am I doing something wrong (which I presume is the most likely case)?

`npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.0.0
npm ERR! Found: @angular/common@11.2.14
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^11.0.8" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from ngx-masonry@12.0.0`

**Comment by wynfred** [comment]
You can just use v11.x of the library. Change it in your package.json.
