### ISSUE TITLE
Masonry layout in Ionic 3 causing white screen effects when scrolling up.

### ISSUE THREAD

**Issue by jayzyaj** [wynfred/ngx-masonry#9]
I have an Ionic 3 where I tried to implement this package and it worked successfully. However in my page I have a **load more event** on scroll function inside an **<ion-scroll>** so when I try to scroll down in order to load some data. The **response data** is added to the `array` the masonry still works but there are some flickering white effect on the image whenever I try to **scroll up**. Any thoughts on this?

**Comment by wynfred** [comment]
Feel free to reopen if you can provide an example project that reproduces the issue :)
